name: Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user: 'Yash1889'
          # Add any additional parameters you need, like:
          # output: 'output/github-contribution-grid-snake.gif'
      - name: Commit and Push
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          git add output/github-contribution-grid-snake.gif
          git commit -m "Update snake gif"
          git push
