name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Yash1889
          gif_out_path: dist/github-contribution-grid-snake.gif  # Path for the GIF
          svg_out_path: dist/github-contribution-grid-snake.svg  # Path for the SVG

      - name: Check the status
        run: git status

      - name: Commit and Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Ensure this is the branch you want to push to
          force: true

